### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by theboss388** [roots/wp-h5bp-htaccess#10]
I seem to be having a few problems with this.

Upon initial install of WordPress, and my theme, it does in fact create the .htaccess with the content from the h5bp-htaccess file as expected. The issue comes when editing that file and reuploading it.

I am expecting the .htaccess file in the root directory to update with the edited content, but it doesn't. I have tried flushing permalinks and this also has no affect.

The only way I am able to get it to update is to completely remove the .htaccess file from the server, then flush the permalinks.

Am I missing something here?

**Comment by retlehs** [comment]
unless something changed in recent wp versions, it *should* update with the edited content on flushing permalinks

(personally, i haven't used this plugin in years because of nginx)

cc @QWp6t

**Comment by theboss388** [comment]
Definitely not playing ball.

I have tried as a plugin, and by inserting direct in to my functions.php file.

Like I say, it works initially, but it seems to fail at overwriting it once it has been changed.

**Comment by QWp6t** [comment]
Yeah, it gets pretty weird at times. It will sometimes throw a fatal error saying that a certain function (`extract_with_markers()`, I believe) doesn't exist. 

I figured it was either a known issue or that it was because I use it as a mu-plugin (so I figured timing was different from a normal plugin, which caused weirdness).

Conversely, `insert_with_markers()` and `extract_from_markers()` are both marked as *internal*, so if we're going to dive into this, I suppose starting there might be a good spot..

**Comment by retlehs** [comment]
i have spent a stupid amount of hours over the years debugging issues that came from inserting rules into `.htaccess` (from both this and the old clean URLs rewrites), and have zero motivation for messing with that ever again (because nginx)

if someone finds a fix and wants to submit a PR, that would be great, but as far as i am concerned this plugin is abandoned :warning:

**Comment by QWp6t** [comment]
I stopped using this plugin because I put these rules in my httpd.conf file. But I'll check it out, and if it looks easy I'll send a PR.

**Comment by retlehs** [comment]
closed by #11
